site_title: Brent's Site
name: Brent Hughes
email: brent@brentahughes.com
phone: (469)-657-9183
project_source: https://github.com/brentahughes/brentahughes.com
github:
  username: brentahughes
gitlab:
  username: bah2830
  user_id: 31161
social_links:
  - https://github.com/bah2830
  - https://gitlab.com/u/bah2830
  - https://www.linkedin.com/in/brent-hughes
  - https://www.facebook.com/bah2830
  - https://twitter.com/bah2830
